### ISSUE TITLE
Weapons not showing up

### ISSUE THREAD

**Issue by itsjeroentje** [ESX-Org/esx_weaponshop#40]
When i open my legal gun shops i get no weapons and when i open the illegal gunshop i also do not get any weapons, i checked if everything was like the DB but i still wont get to see weapons.

**Comment by ElPumpo** [comment]
rerun the sql

**Comment by itsjeroentje** [comment]
What exactly do you mean with returning it?
Bec i checked the server.lua and checked the newest SQL file

**Comment by itsjeroentje** [comment]
> rerun the sql

What exactly do you mean with returning it?
Bec i checked the server.lua and checked the newest SQL file

**Comment by itsjeroentje** [comment]
And if the server restarts the marker doesnt work, after restarting the resource it self it wil work without any weapons in it. 

Error resuming coroutine: client/main.lua:89: attempt to index a nil value (field 'Math')
client/main.lua:79: in function 'OpenShopMenu'
client/maub.lua:198: in function <client/main.lua:182>

**Comment by ElPumpo** [comment]
Then its because you havent updated esx. Dont update anything if youre not gonna update esx too
