### ISSUE TITLE
Any way to buy ammo?

### ISSUE THREAD

**Issue by lvp11** [ESX-Org/esx_weaponshop#45]
Hey,

Any way to buy ammo?

Thanks.

**Comment by HighlineUK** [comment]
good question. How do we get around this?

**Comment by lvp11** [comment]
Still looking for a way, got anything?

**Comment by 8qBITs** [comment]
Yes same issue

**Comment by Mart475** [comment]
How do i set up buying ammo?

**Comment by feqan590** [comment]
i can't too setup ammo shop

**Comment by Mart475** [comment]
I found out how to fix this, i added a script called esx_extraitems and it adds weapon clips to the shop, it's the only way around this issue. :) Thank me later.

**Comment by ProdigyOfficial** [comment]
You can edit the code in order to support clips.

**Comment by Miami-12** [comment]
Are there any new updates on this topic?
