### ISSUE TITLE
Weaponshop doesn't give weapons.

### ISSUE THREAD

**Issue by cooki143** [ESX-Org/esx_weaponshop#49]
No error pops up in console.
Issue on video: https://www.youtube.com/watch?v=mBqMPT2skFo

**Comment by ChapiChapi** [comment]
I have the same problem

**Comment by Ninjabones** [comment]
exactly as the video shows is my situation as well. it knows you bought/own the gun but doesn't give inventory item/gun or show in weapon wheel either.

**Comment by ChapiChapi** [comment]
@cooki143 @Ninjabones I solved the issue by restauring es_extended

**Comment by Ninjabones** [comment]
re-installed es_extended. same issue. re-ran sql. -- no changes.

**Comment by ChapiChapi** [comment]
> re-installed es_extended. same issue. re-ran sql. -- no changes.

if you use the command giveweapon? it works? for you? If it does not work for you, in my case, even with the command it dosen't give a weapon? are you modify es_admin2?

**Comment by Ninjabones** [comment]
Command 'giveweapon' entered..
Error running call reference function for resource es_extended: citizen:/scripting/lua/scheduler.lua:405: @es_extended/server/commands.lua:169: attempt to index a nil value (local 'xPlayer')
stack traceback:
        @es_extended/server/commands.lua:169: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:391: in function <citizen:/scripting/lua/scheduler.lua:390>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:390: in function <citizen:/scripting/lua/scheduler.lua:389>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:405: in function <citizen:/scripting/lua/scheduler.lua:374>
Error running system event handling function for resource essentialmode: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: citizen:/scripting/lua/MessagePack.lua:830: missing bytes
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow'
        citizen:/scripting/lua/MessagePack.lua:465: in field 'any'
        citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack'
        citizen:/scripting/lua/scheduler.lua:628: in field 'cmd'
        @essentialmode/server/main.lua:185: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>

**Comment by Ninjabones** [comment]
es_admin2 no modifications aside from the removal of F2 for inventory HUD mod with vehicle trunk.

**Comment by Ninjabones** [comment]
F8 Console while in-game. Read up the log list and look for start of errors. I found an error for es_extended in the client/main.lua. I discovered I deleted a line spacing that shouldn't have been when I was disabling the F2 script to allow another inventory HUD.  
Solved more than just my weaponshop issues!

**Comment by rafakid** [comment]
what line you deleted @Ninjabones ?
